//
//  Gauge.swift
//  KnitOnCommandLineApp
//
//  Created by CAROLYN STEELE on 11/27/17.
//  Copyright © 2017 CAROLYN STEELE. All rights reserved.
//

import Foundation

struct Gauge {
    
    //Mark: Properties
    private var isRowGaugeAutoGenerated = true
    private var explicitRowGauge: Float?
    var stitchGauge: Float
    var rowGauge: Float? {
        get {
            if self.isRowGaugeAutoGenerated {
                return 5/4*self.stitchGauge
            }
            else {
                return self.explicitRowGauge
            }
        }
        set(newValue) {
            self.explicitRowGauge = newValue
            self.isRowGaugeAutoGenerated = false
        }
    }
    
    //MARK: Initialization
    
    init(stitchGauge: Float) {
        self.stitchGauge = stitchGauge
        self.isRowGaugeAutoGenerated = true
    }
    
    init(stitchGauge: Float, rowGauge: Float){
        self.stitchGauge = stitchGauge
        self.rowGauge = rowGauge
        self.isRowGaugeAutoGenerated = false
    }
    
    //MARK: Methods
    
    public func getIsRowGaugeAutoGenerated() -> Bool {
        return self.isRowGaugeAutoGenerated
    }
    
}
